version: "3.8"

networks:
  cloudflared_network:
    external: true

services:
  coupon:
    container_name: coupon-api
    image: walterdallatorre/coupon-load-test:latest
    ports:
      - "5071:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=5071
      - SWAGGER_SERVER_URL=https://coupon.walterdalla.uk
    restart: unless-stopped
    networks:
      - cloudflared_network